name: Build Docker Image

on:
  workfflow_call:
    inputs:
      image_name:
        type: string
        description: 'The name of the image to build (e.g. "my-app-image")'
        required: true
      dockerfile_path:
        type: string
        description: 'The path to the Dockerfile to build (e.g. ./Dockerfile or ./app/Dockerfile)'
        required: false
        default: '.'
      context_path:
        type: string
        description: 'The path to the context to build (Files to be copied to the image, e.g. ".")'
        required: false
        default: '.'
      registry_username:
        type: string
        description: 'The username of the registry to push the image to'
        required: true

    secrets:
      REGISTRY_TOKEN:
        description: 'The token of the registry to push the image to'
        required: true

    outputs:
      image-tag:
        description: 'The tag of the image to build.'
        value: ${{ jobs.build_image.outputs.full_image_tag }}

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.registry_username }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Get current date for image tag
        id: date
        run:
          echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
      - name: Build and Push Docker image
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context_path }}
          file: ${{ inputs.dockerfile_path }}
          tags: |
            andymartinezot/${{ inputs.image_name }}:latest
            andymartinezot/${{ inputs.image_name }}:${{ steps.date.outputs.date }}
            andymartinezot/${{ inputs.image_name }}:${{ github.sha }}
      - name: Set output variables
        id: vars
        run: |
          echo "full_image_tag=andymartinezot/${{ inputs.image_name }}:latest" >> $GITHUB_OUTPUT
          echo "image_digest=${{ steps.build_and_push.outputs.digest }}" >> $GITHUB_OUTPUT
      - name: Confirm build and deployment
        run: echo "Build and deployment complete. Image --> ${{ vars.full_image_tag }} 🚀✅"


